### ISSUE TITLE
Add SCTP support

### ISSUE THREAD

**Issue by SoniEx2** [spc476/lua-conmanorg#2]

**Comment by spc476** [comment]
Per the [Wikipedia page on SCTP](https://en.wikipedia.org/wiki/Stream_Control_Transmission_Protocol) not all operating systems support SCTP natively, so depending upon your usecase, you might have to go with a third party, which is beyond the scope of this module.

But if you are using Linux or Solaris (both of which are supported by the module) then yes, I can add such support.  It might take a bit as I've never worked with SCTP, and the support I do add might be a bit wonky (again, never worked with it).  

I'm surprised you are using this instead of `luasocket` so if you don't mind my asking, why?  Don't get me wrong, I'm rather happy someone is using this, but I am curious as to the reasoning to select this one.

**Comment by SoniEx2** [comment]
This has unix sockets.

**Comment by spc476** [comment]
I will not be adding support for SCTP within the immediate future.  The primary reason for this is that I do not have access to a system that supports SCTP [1], so I would be unable to actually test the support.

The secondary reason is that SCTP has its own system calls, `sctp_bindx()`, `sctp_connectx()`', `sctp_getpaddrs()`, `sctp_getladdrs()`, `scpt_sendmsg()` and `scpt_recvmsg()`.  It also has a few functions that don't exist for TCP or UDP like `sctp_opt_info()` and `sctp_peeloff()`.  There are other concepts to SCTP than just support, such as associations, notifications and sub-sessions. Even if my systems supported it, it would take me longer than I expected to get familiar enough with SCTP to support it adequately.

So I am sad to say, I am closing this request.

[1] Yes, Linux "supports" it, but the systems I have access to currently do not have it enabled.  I am not in a position to reinstall my operating system(s) to enable the feature.

**Comment by SoniEx2** [comment]
Uh, where did you find those functions?

I just use `socket(AF_INET6, SOCK_SEQPACKET, IPPROTO_SCTP)` and `sendmsg` and `recvmsg` and stuff???

**Comment by spc476** [comment]
From the book _Unix Network Programming Volume 1, Third edition_ by Stevens, Fenner and Rudoff.  Specifically, chatpers 9, 10 and 23.
